/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const SessionInfo = IDL.Record({
  'sessionLabel' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'isActive' : IDL.Bool,
  'sessionId' : SessionId,
});
export const RoomStatus = IDL.Variant({
  'OCCUPIED' : IDL.Null,
  'EMPTY' : IDL.Null,
});
export const Block = IDL.Variant({
  'C_BLOCK' : IDL.Null,
  'R_BLOCK' : IDL.Null,
  'M_BLOCK' : IDL.Null,
});
export const Room = IDL.Record({
  'id' : IDL.Text,
  'status' : RoomStatus,
  'occupiedBy' : IDL.Opt(IDL.Text),
  'currentSession' : SessionId,
  'block' : Block,
});

export const idlService = IDL.Service({
  'getClusterHoliday' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], ['query']),
  'getCurrentSession' : IDL.Func([], [SessionInfo], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getRoomsForDay' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(Room)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const SessionInfo = IDL.Record({
    'sessionLabel' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'isActive' : IDL.Bool,
    'sessionId' : SessionId,
  });
  const RoomStatus = IDL.Variant({ 'OCCUPIED' : IDL.Null, 'EMPTY' : IDL.Null });
  const Block = IDL.Variant({
    'C_BLOCK' : IDL.Null,
    'R_BLOCK' : IDL.Null,
    'M_BLOCK' : IDL.Null,
  });
  const Room = IDL.Record({
    'id' : IDL.Text,
    'status' : RoomStatus,
    'occupiedBy' : IDL.Opt(IDL.Text),
    'currentSession' : SessionId,
    'block' : Block,
  });
  
  return IDL.Service({
    'getClusterHoliday' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], ['query']),
    'getCurrentSession' : IDL.Func([], [SessionInfo], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getRoomsForDay' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Room)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };